### ISSUE TITLE
Unable to build any code/example due to reflect-metadata

### ISSUE THREAD

**Issue by euphario** [marcj/marshal.ts#39]
Hello,

I was hoping to get a little bit of help.

I keep getting this error no matter what I try;
That's on any decorator, the minute I remove any f decorator, everything is fine.

../node_modules/@marcj/marshal/src/decorators.ts:1265
        const isMethod = propertyOrMethodName && Reflect.hasMetadata('design:returntype', target, propertyOrMethodName) && !isNumber(parameterIndexOrDescriptor);

I cannot work out what is the problem with my environment. I tried first in a new NestJS app and I had no issues, but even in the most basic Typescript app that I have I get this error.

Even the examples don't work. 

```
import { f, plainToClass, uuid } from '@marcj/marshal';

class SubModel {
    @f label: string = '';
}

export enum Plan {
    DEFAULT,
    PRO,
    ENTERPRISE
}

class SimpleModel {
    @(f.primary().uuid())
    id: string = uuid();

    @f.array(String)
    tags: string[] = [];

    @f.optional() //binary
    picture?: ArrayBuffer;

    @f
    type: number = 0;

    @f.enum(Plan, /*allowLabelsAsValue=*/ true)
    plan: Plan = Plan.DEFAULT;

    @f
    created: Date = new Date();

    @f.array(SubModel)
    children: SubModel[] = [];

    @f.map(SubModel)
    childrenMap: { [key: string]: SubModel } = {};

    constructor(
        @(f.index().asName('name')) //asName is required for minimized code
        public name: string
    ) {}
}

//data comes usually from files or http request
const instance = plainToClass(SimpleModel, {
    name: 'myName',
    tags: ['foo', 'bar'],
    plan: 'PRO',
    created: 'Sat Oct 13 2018 14:17:35 GMT+0200',
    children: [{ label: 'foo' }],
    childrenMap: { foo: { label: 'foo' } }
});
console.log(instance);

```

package.json
```json
{
  "name": "proton-server",
  "version": "0.0.1",
  "description": "",
  "author": "",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "start": "node -r ts-node/register ./src/server.ts",
    "dev": "nodemon ",
    "build": "tsc",
    "script": "cd src/scripts && ts-node"
  },
  "dependencies": {
    "@marcj/marshal": "^2.1.4"
  },
  "peerDependencies": {
    "reflect-metadata": "^0.1.12"
  },
  "devDependencies": {
    "reflect-metadata": "^0.1.13",
    "@types/node": "^14.0.5",
    "nodemon": "^2.0.3",
    "ts-node": "^8.9.1",
    "typescript": "^3.8.3"
  }
}
```
tsconfig.json
```json
{
    "compilerOptions": {
        "target": "es2019",
        "module": "commonjs",
        "declaration": true,
        "removeComments": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "sourceMap": true,
        "outDir": "./dist",
        "baseUrl": "./",
        "incremental": true,
        "esModuleInterop": true,
        "lib": ["es2020"],
        "resolveJsonModule": true
    },
    "exclude": ["node_modules", "dist"]
}
```

**Comment by marcj** [comment]
I don't see any error message?

**Comment by euphario** [comment]
```
/home/thomas/proton4-server/node_modules/@marcj/marshal/src/decorators.ts:1265
        const isMethod = propertyOrMethodName && Reflect.hasMetadata('design:returntype', target, propertyOrMethodName) && !isNumber(parameterIndexOrDescriptor);
                                                         ^
TypeError: Reflect.hasMetadata is not a function
    at fn (/home/thomas/proton4-server/node_modules/@marcj/marshal/src/decorators.ts:1265:58)
    at __decorate (/home/thomas/proton4-server/src/controllers/sark2.ts:5:110)
    at /home/thomas/proton4-server/src/controllers/sark2.ts:12:5
    at Object.<anonymous> (/home/thomas/proton4-server/src/controllers/sark2.ts:30:3)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Module.m._compile (/home/thomas/proton4-server/node_modules/ts-node/src/index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Object.require.extensions.<computed> [as .ts] (/home/thomas/proton4-server/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
```

**Comment by marcj** [comment]
You have to import

import 'reflect-metadata';

to make it work. Hm think I don't have that in the examples, but I will do later.

**Comment by euphario** [comment]
Oh my, that was simple, I feel a little stupid not having thought about it, but I could not find an example that imports it.
Yes indeed, I need to import reflect-metadata.

Thank you!
